SIS/SIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('home.urls', namespace='home')),
    path('users/', include('sis_users.urls', namespace='sis_users')),
    path('classes/', include('class_groups.urls', namespace='class_groups'))
]

SIS/class_groups/urls.py
from django.urls import path
from class_groups.views import SchoolView, YearView, BandView, SetView

app_name = 'class_groups'

urlpatterns = [
    path('', SchoolView.as_view(), name='school-view'),
    path('<year>/', YearView.as_view(), name='year-view'),
    path('<year>/<band>/', BandView.as_view(), name='band-view'),
    path('<year>/<band>/<set>', SetView.as_view(), name='set-view')
]

SIS/sis_users/urls.py
from django.urls import path
from sis_users.views import (
    AdminList,
    AdminDetail,
    StaffList,
    StaffDetail,
    StudentList,
    StudentDetail,
)

app_name = 'sis_users'

urlpatterns = [
    path('admins', AdminList.as_view(), name='admin-list'),
    path('admins/<username>', AdminDetail.as_view(), name='admin-detail'),
    path('staff', StaffList.as_view(), name='staff-list'),
    path('staff/<username>', StaffDetail.as_view(), name='staff-detail'),
    path('students', StudentList.as_view(), name='student-list'),
    path('students/<username>', StudentDetail.as_view(), name='student-detail'),
]

SIS/class_groups/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db import DataError
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from class_groups.choices import YEAR_CHOICES, BAND_CHOICES, SET_CHOICES

class School(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Year(models.Model):
    school = models.ForeignKey('School', on_delete=models.SET_NULL, null=True)
    value = models.IntegerField(choices=YEAR_CHOICES, null=False)

    def __str__(self):
        return self.get_value_display()

    def validate_unique(self, *args, **kwargs):
        super().validate_unique(*args, **kwargs)
        qs = Year.objects.filter(value=self.value)
        if qs.filter(school=self.school).exists():
            raise ValidationError('Years must be unique within each school.')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.validate_unique()
        super().save(*args, **kwargs)

class Band(models.Model):
    year = models.ForeignKey('Year', on_delete=models.SET_NULL, null=True)
    value = models.CharField(max_length=1, choices=BAND_CHOICES, null=False)

    def __str__(self):
        year = self.year.get_value_display()
        band = self.get_value_display()
        return f'{year} - {band}'

    def validate_unique(self, *args, **kwargs):
        super().validate_unique(*args, **kwargs)
        qs = Band.objects.filter(value=self.value)
        if qs.filter(year=self.year).exists():
            if qs.filter(year__school=self.year.school).exists():
                raise ValidationError('Each band must be unique within each year group.')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.validate_unique()
        super().save(*args, **kwargs)

class Set(models.Model):
    band = models.ForeignKey('Band', on_delete=models.SET_NULL, null=True)
    value = models.IntegerField(choices=SET_CHOICES, null=False)
    subjects = models.ManyToManyField('Subject')
    teachers = models.ManyToManyField('sis_users.Staff')

    def __str__(self):
        year = self.band.year.get_value_display()
        band = self.band.get_value_display()
        set = self.get_value_display()
        return f'{year} - {band} - {set}'

    def validate_unique(self, *args, **kwargs):
        super().validate_unique(*args, **kwargs)
        qs = Set.objects.filter(value=self.value)
        if qs.filter(band=self.band).exists():
            if qs.filter(band__year=self.band.year).exists():
                if qs.filter(band__year__school=self.band.year.school).exists():
                    raise ValidationError('Each set must be unique within each band.')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.validate_unique()
        super().save(*args, **kwargs)

class Subject(models.Model):
    name = models.CharField(max_length=20, null=True)
    teachers = models.ManyToManyField('sis_users.Staff')

    def __str__(self):
        return self.name

SIS/sis_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.apps import apps
from class_groups.choices import YEAR_CHOICES, BAND_CHOICES, SET_CHOICES

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email}'

class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email}'

    @property
    def class_set(self):
        return self.set_set.order_by('band__year__value', 'band__value', 'value')

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    set = models.ForeignKey('class_groups.Set',
                                    on_delete=models.SET_NULL,
                                    null=True,
                                    blank=True)

    def __str__(self):
        return f'{self.user.email}'

class UserState(models.Model):
    '''
        Model to hold whether an email address is a staff member or a student.
        Table will be populated by an external script (run once every hour),
        that will use Google App Manager (GAM) to check email groups and
        determine if a user is a staff member or a student.
    '''
    email = models.EmailField(default='', unique=True)
    staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    year = models.IntegerField(choices=YEAR_CHOICES, null=True)
    band = models.CharField(max_length=1, choices=BAND_CHOICES, null=True)
    set = models.IntegerField(choices=SET_CHOICES, null=True)

    def __str__(self):
        return f'{self.email} - Admin: {self.is_admin} - Staff: {self.staff}'

@receiver(post_save, sender=User)
def create_student_or_staff(sender, instance, created, **kwargs):
    if created:
        state = UserState.objects.get(
            email=instance.email
        )
        if state.staff:
            if state.is_admin:
                Admin.objects.create(
                    user=instance
                )
            Staff.objects.create(
                user=instance
            )
        else:
            class_instance = None
            if state.year and state.band and state.set:
                class_model = apps.get_model('class_groups.Set')
                class_instance = class_model.objects.get(
                    value=state.set,
                    band__value=state.band,
                    band__year__value=state.year
                )
            Student.objects.create(
                user=instance,
                set=class_instance
            )
            

@receiver(post_save, sender=User)
def save_user(sender, instance, **kwargs):
    if hasattr(instance, 'admin'):
        instance.admin.save()
    if hasattr(instance, 'staff'):
        instance.staff.save()
    if hasattr(instance, 'student'):
        instance.student.save()

SIS/class_groups/views.py
from django.views.generic import ListView, TemplateView, DetailView
from django.conf import settings
from sis_users.mixins import LoginRequiredMessageMixin
from class_groups.models import School, Year, Band, Set

class SchoolView(LoginRequiredMessageMixin, DetailView):
    template_name = 'class_groups/school_page.html'
    model = School

    def get_object(self, queryset=None):
        # get the name of the school defined in settings / environment variable
        return School.objects.get(name=settings.SCHOOL_NAME)

class YearView(LoginRequiredMessageMixin, DetailView):
    template_name = 'class_groups/year_page.html'
    model = Year

    def get_object(self, queryset=None):
        return Year.objects.get(
            value=self.kwargs['year']
        )

class BandView(LoginRequiredMessageMixin, DetailView):
    template_name = 'class_groups/band_page.html'
    model = Band

    def get_object(self, queryset=None):
        return Band.objects.get(
            value=self.kwargs['band'],
            year__value=self.kwargs['year']
        )

class SetView(LoginRequiredMessageMixin, DetailView):
    template_name = 'class_groups/set_page.html'
    model = Set

    def get_object(self, queryset=None):
        return Set.objects.get(
            value=self.kwargs['set'],
            band__value=self.kwargs['band'],
            band__year__value=self.kwargs['year']
        )

SIS/class_groups/templates/class_groups/band_class_page.html
{% extends 'class_groups/base_class_page.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">{{ band }}</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <a class="row">
        {% for set in band.set_set.all %}
            <div class="col-sm">
                <a href="{% url 'class_groups:set-view' band.year.value band.value set.value %}">
                    <h3 class="text-center">{{ set.get_value_display }}</h3>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/band_page.html
{% extends 'class_groups/base.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">{{ band }}</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <a class="row">
        {% for set in band.set_set.all %}
            <div class="col-sm">
                <a href="{% url 'class_groups:set-view' band.year.value band.value set.value %}">
                    <h3 class="text-center">{{ set.get_value_display }}</h3>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/base.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'class_groups/common_styles.css' %}" />
{% endblock %}

{% block content %}
    {% block header %}
    {% endblock %}
    {% block class_list %}
    {% endblock %}
{% endblock %}

SIS/class_groups/templates/class_groups/base_class_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'class_groups/common_styles.css' %}" />
{% endblock %}

{% block content %}
    {% block header %}
    {% endblock %}
    {% block class_list %}
    {% endblock %}
{% endblock %}

SIS/class_groups/templates/class_groups/genericlistview.html
{% extends 'base.html' %}
{% block content %}
    {% block header %}
    {% endblock %}
    {% block class_list %}
    {% endblock %}
{% endblock %}

SIS/class_groups/templates/class_groups/school_class_page.html
{% extends 'class_groups/base_class_page.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">All Classes</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        {% for year in school.year_set.all %}
            <div class="col-sm-4">
                <a href="{% url 'class_groups:year-view' year.value %}">
                    <h3 class="text-center">{{ year.get_value_display }}</h3>
                </a>
                {% for band in year.band_set.all %}
                    <a href="{% url 'class_groups:band-view' year.value band.value %}">
                        <h4 class="text-center">{{ band.get_value_display }}</h4>
                    </a>
                    {% for set in band.set_set.all %}
                        <a href="{% url 'class_groups:set-view' year.value band.value set.value %}">
                            <h5 class="text-center">{{ set.get_value_display }}</h5>
                        </a>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/school_page.html
{% extends 'class_groups/base.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">All Classes</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        {% for year in school.year_set.all %}
            <div class="col-sm-4">
                <a href="{% url 'class_groups:year-view' year.value %}">
                    <h3 class="text-center">{{ year.get_value_display }}</h3>
                </a>
                {% for band in year.band_set.all %}
                    <a href="{% url 'class_groups:band-view' year.value band.value %}">
                        <h4 class="text-center">{{ band.get_value_display }}</h4>
                    </a>
                    {% for set in band.set_set.all %}
                        <a href="{% url 'class_groups:set-view' year.value band.value set.value %}">
                            <h5 class="text-center">{{ set.get_value_display }}</h5>
                        </a>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/school_view.html
{% extends 'class_groups/genericlistview.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'class_groups/common_styles.css' %}" />
{% endblock %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">All Classes</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        {% for year in years %}
            <div class="col-sm-4">
            <a href="{% url 'class_groups:year-view' year.0 %}">
            <h3 class="text-center">{{ year.1 }}</h3>
            </a>
            {% for band in bands %}
                <a href="{% url 'class_groups:band-view' year.0 band.0 %}">
                <h4 class="text-center">{{ band.1 }}</h4>
                </a>
                {% for set in sets %}
                    <a href="{% url 'class_groups:set-view' year.0 band.0 set.0 %}">
                    <h5 class="text-center">Set {{ set.1 }}</h5>
                    </a>
                {% endfor %}
            {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/set_page.html
{% extends 'class_groups/base.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">{{ set }}</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        <div class="col-sm">
            <h3 class="text-center">Students</h3>
            {% for student in set.student_set.all %}
                <ul>
                <li>
                    <a href="{% url 'sis_users:student-detail' student.user.username %}">{{ student.user.username }}</a>
                </li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/year_class_page.html
{% extends 'class_groups/base_class_page.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">{{ year }}</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        {% for band in year.band_set.all %}
            <div class="col-sm-6">
                <a href="{% url 'class_groups:band-view' year.value band.value %}">
                    <h3 class="text-center">{{ band.get_value_display }}</h3>
                </a>
                {% for set in band.set_set.all %}
                    <a href="{% url 'class_groups:set-view' year.value band.value set.value %}">
                        <h4 class="text-center">{{ set.get_value_display }}</h4>
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

SIS/class_groups/templates/class_groups/year_page.html
{% extends 'class_groups/base.html' %}

{% block header %}
    <div class="row spacer">
        <div class="col-sm">
            <h2 class="text-center">{{ year }}</h2>
        </div>
    </div>
{% endblock %}

{% block class_list %}
    <div class="row">
        {% for band in year.band_set.all %}
            <div class="col-sm-6">
                <a href="{% url 'class_groups:band-view' year.value band.value %}">
                    <h3 class="text-center">{{ band.get_value_display }}</h3>
                </a>
                {% for set in band.set_set.all %}
                    <a href="{% url 'class_groups:set-view' year.value band.value set.value %}">
                        <h4 class="text-center">{{ set.get_value_display }}</h4>
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}