SIS/SIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('home.urls', namespace='home')),
    path('users/', include('sis_users.urls', namespace='sis_users')),
    path('classes/', include('class_groups.urls', namespace='class_groups'))
]

SIS/class_groups/urls.py
from django.urls import path
from class_groups.views import SchoolView, YearView, BandView, SetView

app_name = 'class_groups'

urlpatterns = [
    path('', SchoolView.as_view(), name='school-view'),
    path('<year>/', YearView.as_view(), name='year-view'),
    path('<year>/<band>/', BandView.as_view(), name='band-view'),
    path('<year>/<band>/<set>', SetView.as_view(), name='set-view')
]

SIS/home/urls.py
from django.urls import path
from home.views import Home, Logout

app_name = 'home'

urlpatterns = [
    path('', Home.as_view(), name='home-page'),
    path('logout', Logout.as_view(), name='logout')
]

SIS/sis_users/urls.py
from django.urls import path
from sis_users.views import (
    AdminList,
    AdminDetail,
    StaffList,
    StaffDetail,
    StudentList,
    StudentDetail,
)

app_name = 'sis_users'

urlpatterns = [
    path('admins', AdminList.as_view(), name='admin-list'),
    path('admins/<username>', AdminDetail.as_view(), name='admin-detail'),
    path('staff', StaffList.as_view(), name='staff-list'),
    path('staff/<username>', StaffDetail.as_view(), name='staff-detail'),
    path('students', StudentList.as_view(), name='student-list'),
    path('students/<username>', StudentDetail.as_view(), name='student-detail'),
]

SIS/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ page_title }}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        {% block head %}
        {%  endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'home:home-page' %}">School Homepage</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if user.staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'class_groups:school-view' %}">Classes</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% if user.staff %}{% url 'sis_users:staff-detail' user %}{% else %}{% url 'sis_users:student-detail' user %}{% endif %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                </li>
            </ul>
          </div>

        {% else %}

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url "social:begin" "google-oauth2" %}?next={{request.get_full_path}}">Login</a>
                  </li>
              </ul>
          </div>


        {% endif %}

        </nav>


        <div class="container-fluid">
            {% block content %}{% endblock content %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </body>
</html>