SIS/SIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('home.urls', namespace='home')),
    path('users/', include('sis_users.urls', namespace='sis_users')),
    path('classes/', include('class_groups.urls', namespace='class_groups'))
]

SIS/class_groups/urls.py
from django.urls import path
from class_groups.views import SchoolView, YearView, BandView, SetView

app_name = 'class_groups'

urlpatterns = [
    path('', SchoolView.as_view(), name='school-view'),
    path('<year>/', YearView.as_view(), name='year-view'),
    path('<year>/<band>/', BandView.as_view(), name='band-view'),
    path('<year>/<band>/<set>', SetView.as_view(), name='set-view')
]

SIS/sis_users/urls.py
from django.urls import path
from sis_users.views import (
    AdminList,
    AdminDetail,
    StaffList,
    StaffDetail,
    StudentList,
    StudentDetail,
)

app_name = 'sis_users'

urlpatterns = [
    path('admins', AdminList.as_view(), name='admin-list'),
    path('admins/<username>', AdminDetail.as_view(), name='admin-detail'),
    path('staff', StaffList.as_view(), name='staff-list'),
    path('staff/<username>', StaffDetail.as_view(), name='staff-detail'),
    path('students', StudentList.as_view(), name='student-list'),
    path('students/<username>', StudentDetail.as_view(), name='student-detail'),
]

SIS/sis_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.apps import apps
from class_groups.choices import YEAR_CHOICES, BAND_CHOICES, SET_CHOICES

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email}'

class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email}'

    @property
    def class_set(self):
        return self.set_set.order_by('band__year__value', 'band__value', 'value')

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    set = models.ForeignKey('class_groups.Set',
                                    on_delete=models.SET_NULL,
                                    null=True,
                                    blank=True)

    def __str__(self):
        return f'{self.user.email}'

class UserState(models.Model):
    '''
        Model to hold whether an email address is a staff member or a student.
        Table will be populated by an external script (run once every hour),
        that will use Google App Manager (GAM) to check email groups and
        determine if a user is a staff member or a student.
    '''
    email = models.EmailField(default='', unique=True)
    staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    year = models.IntegerField(choices=YEAR_CHOICES, null=True)
    band = models.CharField(max_length=1, choices=BAND_CHOICES, null=True)
    set = models.IntegerField(choices=SET_CHOICES, null=True)

    def __str__(self):
        return f'{self.email} - Admin: {self.is_admin} - Staff: {self.staff}'

@receiver(post_save, sender=User)
def create_student_or_staff(sender, instance, created, **kwargs):
    if created:
        state = UserState.objects.get(
            email=instance.email
        )
        if state.staff:
            if state.is_admin:
                Admin.objects.create(
                    user=instance
                )
            Staff.objects.create(
                user=instance
            )
        else:
            class_instance = None
            if state.year and state.band and state.set:
                class_model = apps.get_model('class_groups.Set')
                class_instance = class_model.objects.get(
                    value=state.set,
                    band__value=state.band,
                    band__year__value=state.year
                )
            Student.objects.create(
                user=instance,
                set=class_instance
            )
            

@receiver(post_save, sender=User)
def save_user(sender, instance, **kwargs):
    if hasattr(instance, 'admin'):
        instance.admin.save()
    if hasattr(instance, 'staff'):
        instance.staff.save()
    if hasattr(instance, 'student'):
        instance.student.save()

SIS/sis_users/views.py
from django.views.generic import ListView, DetailView
from sis_users.mixins import (
    LoginRequiredMessageMixin,
    BaseAccessMessageMixin
)
from sis_users.models import Admin, Staff, Student

class AdminList(BaseAccessMessageMixin, ListView):
    template_name = 'sis_users/admin_list.html'
    permitted_attributes = ['admin']
    error_message = 'You must be an administrator to access this page.'

    def get_queryset(self):
        return Admin.objects.all()

class StaffList(BaseAccessMessageMixin, ListView):
    template_name = 'sis_users/staff_list.html'
    permitted_attributes = ['admin', 'staff']
    error_message = 'You must be a staff member, or administrator to access this page.'

    def get_queryset(self):
        return Staff.objects.all()

class StudentList(BaseAccessMessageMixin, ListView):
    template_name = 'sis_users/student_list.html'
    permitted_attributes = ['admin', 'staff', 'student']
    error_message = 'You must be a staff member, administrator or student to access this page.'

    def get_queryset(self):
        return Student.objects.all()

class AdminDetail(LoginRequiredMessageMixin, DetailView):
    template_name = 'sis_users/admin_profile.html'

    def get_object(self, queryset=None):
        return Admin.objects.get(user__username=self.kwargs['username'])


class StaffDetail(LoginRequiredMessageMixin, DetailView):
    template_name = 'sis_users/staff_profile.html'

    def get_object(self, queryset=None):
        return Staff.objects.get(user__username=self.kwargs['username'])

class StudentDetail(LoginRequiredMessageMixin, DetailView):
    template_name = 'sis_users/student_profile.html'

    def get_object(self, queryset=None):
        return Student.objects.get(user__username=self.kwargs['username'])

SIS/sis_users/templates/sis_users/admin_list.html
{% extends 'sis_users/base_list.html' %}

{% block header %}
    <h3 class="text-center">Admin List</h3>
{% endblock %}

{% block list %}
    <ul>
        {% for admin in admin_list %}
            <li>
                <a href="{% url 'sis_users:admin-detail' admin.user.username %}">{{ admin.user.username }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

SIS/sis_users/templates/sis_users/admin_profile.html
{% extends 'sis_users/base_profile.html' %}

{% block state %}
Administrator
{% endblock %}

{% block state_specific %}
    <div class="row">
        <h2>This is where admin specific stuff will go.</h2>
    </div>
{% endblock %}

SIS/sis_users/templates/sis_users/base_list.html
{% extends 'base.html' %}

{% block content %}
    {% block header %}
    {% endblock %}
    {% block list %}
    {% endblock %}
{% endblock %}

SIS/sis_users/templates/sis_users/base_profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'sis_users/profile.css' %}" />
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-sm">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ object.user.first_name }}'s {% block state %}{% endblock %}Profile</h3>
                </div>
                <div class="row spacer"></div>
                <div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-lg-12">
                                <table class="table table-user-information">
                                    <tbody>
                                        <tr>
                                            <td>
                                                First Name:
                                            </td>
                                            <td>
                                                {{ object.user.first_name }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Last Name:
                                            </td>
                                            <td>
                                                {{  object.user.last_name }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Email:
                                            </td>
                                            <td>
                                                {{  object.user.email }}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block state_specific %}
    {% endblock %}
{% endblock %}

SIS/sis_users/templates/sis_users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'sis_users/profile.css' %}" />
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-sm">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ object.user.first_name }}'s Profile</h3>
                </div>
                <div class="row spacer"></div>
                <div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-lg-12">
                                <table class="table table-user-information">
                                    <tbody>
                                        <tr>
                                            <td>
                                                First Name:
                                            </td>
                                            <td>
                                                {{ object.user.first_name }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Last Name:
                                            </td>
                                            <td>
                                                {{  object.user.last_name }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Email:
                                            </td>
                                            <td>
                                                {{  object.user.email }}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

SIS/sis_users/templates/sis_users/staff_list.html
{% extends 'sis_users/base_list.html' %}

{% block header %}
    <h3 class="text-center">Staff List</h3>
{% endblock %}

{% block list %}
    <ul>
        {% for staff in staff_list %}
            <li>
                <a href="{% url 'sis_users:staff-detail' staff.user.username %}">{{ staff.user.username }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

SIS/sis_users/templates/sis_users/staff_profile.html
{% extends 'sis_users/base_profile.html' %}

{% block state %}
Staff
{% endblock %}

{% block state_specific %}
    <div class="row">
        <h3>Classes</h3>
            <ul>
                {% for set in object.class_set %}
                    <li><a href="{% url 'class_groups:set-view' set.band.year.value set.band.value set.value %}">{{ set }}</a></li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

SIS/sis_users/templates/sis_users/student_list.html
{% extends 'sis_users/base_list.html' %}

{% block header %}
    <h3 class="text-center">Student List</h3>
{% endblock %}

{% block list %}
    <ul>
        {% for student in student_list %}
            <li>
                <a href="{% url 'sis_users:student-detail' student.user.username %}">{{ student.user.username }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

SIS/sis_users/templates/sis_users/student_profile.html
{% extends 'sis_users/base_profile.html' %}

{% block state %}
Student
{% endblock %}

{% block state_specific %}
    <div class="row">
        <h3>Class:</h3>
        <h4><a href="{% url 'class_groups:set-view' object.set.band.year.value object.set.band.value object.set.value %}">{{ object.set }}</a></h4>
    </div>
{% endblock %}